name: CI

on:
  push:
  pull_request:

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "✅ Build placeholder – workflow runs successfully"
